version: 0.1

default:
    deploy:
        parameters:
            stack_name: bucket-scrubber
            resolve_s3: true
            capabilities:
            - CAPABILITY_IAM
            - CAPABILITY_NAMED_IAM

